export const Reservations = [];

export const Cleanings = [
  {
    Id: 12345,
    Guest: {
      ArrivalDate: "2024-03-25T15:38:05.073Z",
      DepartureDate: "2024-03-25T15:38:05.073Z",
      FirstName: "string",
      LastName: "string",
    },
    Room: {
      Id: 202,
      Code: "202",
      Name: "202",
      Color: "yellow",
    },
    RoomType: {
      Id: 303,
      Code: "SQ",
      Name: "Стандартный двухместный номер с одной кроватью",
      Color: "green",
    },
    GuestLayout: "Adult1Count",
    CleaningType: {
      Id: 5,
      Code: "DC",
      Name: "Dry clean",
      Color: "blue",
    },
    AssignedUser: {
      Login: "string",
      FirstName: "string",
      MiddleName: "string",
      LastName: "string",
      Email: "string",
      IsActive: true,
    },
    CleaningStatus: {
      Id: 1,
      Code: "C",
      Name: "Clean",
      Color: "orange",
    },
    IsOccupied: true,
    ArrivalTime: "22:03",
    InspectionRequired: true,
    IsVisuallyOccupied: true,
    StartedDate: "2024-03-25T15:38:05.073Z",
    CompletedDate: "2024-03-25T15:38:05.073Z",
    CleaningScore: 0,
    CleaningNotes: "string",
    Comment: "string",
    CleaningRefusalTypeId: 0,
    CleaningRefusalDate: "2024-03-25T15:38:05.073Z",
    AllowRefusal: true,
  },
  {
    Id: 12344,
    Guest: {
      ArrivalDate: "2024-03-25T15:38:05.073Z",
      DepartureDate: "2024-03-25T15:38:05.073Z",
      FirstName: "Pavel",
      LastName: "Barmenkov",
    },
    Room: {
      Id: 218,
      Code: "218",
      Name: "218",
      Color: "green",
    },
    RoomType: {
      Id: 404,
      Code: "SQ",
      Name: "Люкс",
      Color: "green",
    },
    GuestLayout: "Adult2Count",
    CleaningType: {
      Id: 6,
      Code: "DC",
      Name: "Dry clean",
      Color: "blue",
    },
    AssignedUser: {
      Login: "string",
      FirstName: "string",
      MiddleName: "string",
      LastName: "string",
      Email: "string",
      IsActive: true,
    },
    CleaningStatus: {
      Id: 2,
      Code: "D",
      Name: "Dirty",
      Color: "red",
    },
    IsOccupied: true,
    ArrivalTime: "22:03",
    InspectionRequired: true,
    IsVisuallyOccupied: true,
    StartedDate: "2024-03-25T15:38:05.073Z",
    CompletedDate: "2024-03-25T15:38:05.073Z",
    CleaningScore: 0,
    CleaningNotes: "string",
    Comment: "string",
    CleaningRefusalTypeId: 0,
    CleaningRefusalDate: "2024-03-25T15:38:05.073Z",
    AllowRefusal: true,
  },
  {
    Id: 12347,
    Guest: {
      ArrivalDate: "2024-03-25T15:38:05.073Z",
      DepartureDate: "2024-03-25T15:38:05.073Z",
      FirstName: "Olga",
      LastName: "Barmenkova",
    },
    Room: {
      Id: 219,
      Code: "219",
      Name: "219",
      Color: "yellow",
    },
    RoomType: {
      Id: 404,
      Code: "SQ",
      Name: "Стандартный двухместный номер с одной кроватью",
      Color: "green",
    },
    GuestLayout: "Adult1Count",
    CleaningType: {
      Id: 5,
      Code: "DC",
      Name: "Dry clean",
      Color: "blue",
    },
    AssignedUser: {
      Login: "string",
      FirstName: "string",
      MiddleName: "string",
      LastName: "string",
      Email: "string",
      IsActive: true,
    },
    CleaningStatus: {
      Id: 2,
      Code: "D",
      Name: "Dirty",
      Color: "red",
    },
    IsOccupied: true,
    ArrivalTime: "22:06",
    InspectionRequired: true,
    IsVisuallyOccupied: true,
    StartedDate: "2024-03-25T15:38:05.073Z",
    CompletedDate: "2024-03-25T15:38:05.073Z",
    CleaningScore: 0,
    CleaningNotes: "string",
    Comment: "string",
    CleaningRefusalTypeId: 0,
    CleaningRefusalDate: "2024-03-25T15:38:05.073Z",
    AllowRefusal: true,
  },
];

export const Hotels = {
  isDefaultHotelId: "2",
  isLoggedInHotelId: "",
  hotels: [
    {
      hotelName: "Hotel1",
      serverAddress: "1111",
      defaultPointOfSales: "",
      defaultPocketCode: "",
      user: { userName: "ab", userPassword: "1", token: "" },
      language: "",
      isLoggedIn: false,
      PropertyId: null,
      id: "1",
    },
    {
      hotelName: "Hotel2",
      serverAddress: "2222",
      defaultPointOfSales: "",
      defaultPocketCode: "",
      user: { userName: "abb", userPassword: "1", token: "" },
      language: "",
      isLoggedIn: false,
      PropertyId: null,
      id: "2",
    },
    {
      hotelName: "Hotel3",
      serverAddress: "3333",
      defaultPointOfSales: "",
      defaultPocketCode: "",
      user: { userName: "abbbb", userPassword: "1", token: "" },
      language: "",
      isLoggedIn: false,
      PropertyId: null,
      id: "3",
    },
  ],
};
